[workspace]
resolver = "3"
members = ["pounce-config", "pounce-daemon", "pounce-server"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"

[workspace.dependencies]
async-trait = "0.1.92"
anyhow = "1.0.104"
nanologger = { version = "0.1.1", features = ["log"] }
send_ctrlc = { version = "0.6.0", features = ["tokio"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
uuid = { version = "1.26.1", features = ["serde", "v4"] }